metadata/src/objects/FObjectOne__c.object
<CustomObject>
    <description>An object used in Forccea test methods.</description>
    <fields>
        <fullName>TestCheckbox__c</fullName>
        <defaultValue>false</defaultValue>
        <label>TestCheckbox</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>TestCurrency__c</fullName>
        <label>TestCurrency</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>TestDate__c</fullName>
        <label>TestDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TestDatetime__c</fullName>
        <label>TestDatetime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TestDecimal__c</fullName>
        <label>TestDecimal</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TestEmail__c</fullName>
        <label>TestEmail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>TestInteger__c</fullName>
        <label>TestInteger</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TestLookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TestLookup</label>
        <referenceTo>FObjectTwo__c</referenceTo>
        <relationshipLabel>FObjectOnes</relationshipLabel>
        <relationshipName>FObjectOnes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TestMultiPicklistA__c</fullName>
        <label>TestMultiPicklistA</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>d1</fullName>
                </value>
                <value>
                    <fullName>d2</fullName>
                </value>
                <value>
                    <fullName>d3</fullName>
                </value>
                <value>
                    <fullName>d4</fullName>
                </value>
                <value>
                    <fullName>d5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TestPercent__c</fullName>
        <label>TestPercent</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TestPhone__c</fullName>
        <label>TestPhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>TestPicklistA__c</fullName>
        <description>This field doesn&apos;t have a controlling field.</description>
        <label>TestPicklistA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>a0</fullName>
                </value>
                <value>
                    <fullName>a1</fullName>
                </value>
                <value>
                    <fullName>a2</fullName>
                </value>
                <value>
                    <fullName>a3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TestPicklistB__c</fullName>
        <description>This field has the TestPicklistA as a controlling field.</description>
        <label>TestPicklistB</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TestPicklistA__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>b0</fullName>
                </value>
                <value>
                    <fullName>b1</fullName>
                </value>
                <value>
                    <fullName>b2</fullName>
                </value>
                <value>
                    <fullName>b3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TestPicklistC__c</fullName>
        <description>This field has the TestPicklistB as a controlling field.</description>
        <label>TestPicklistC</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TestPicklistB__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>c0</fullName>
                </value>
                <value>
                    <fullName>c1</fullName>
                </value>
                <value>
                    <fullName>c2</fullName>
                </value>
                <value>
                    <fullName>c3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TestPicklistD__c</fullName>
        <description>This field has the TestCheckbox as a controlling field.</description>
        <label>TestPicklistD</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TestCheckbox__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>d0</fullName>
                </value>
                <value>
                    <fullName>d1</fullName>
                </value>
                <value>
                    <fullName>d2</fullName>
                </value>
                <value>
                    <fullName>d3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TestTextAreaLong__c</fullName>
        <label>TestTextAreaLong</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TestTextAreaRich__c</fullName>
        <label>TestTextAreaRich</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>TestTextArea__c</fullName>
        <label>TestTextArea</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>TestTextRequired__c</fullName>
        <label>TestTextRequired</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TestText__c</fullName>
        <label>TestText</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TestTime__c</fullName>
        <label>TestTime</label>
        <type>Time</type>
    </fields>
    <fields>
        <fullName>TestUrl__c</fullName>
        <label>TestUrl</label>
        <type>Url</type>
    </fields>
    <label>FObjectOne</label>
    <nameField>
        <displayFormat>FO1-{00000}</displayFormat>
        <label>FObjectOne Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FObjectOnes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

metadata/src/objects/FObjectTwo__c.object
<CustomObject>
    <description>An object used in Forccea test methods.</description>
    <fields>
        <fullName>TestPicklistA__c</fullName>
        <description>This field doesn&apos;t have a controlling field and its values are restricted.</description>
        <inlineHelpText>This field doesn&apos;t have a controlling field and its values are restricted.</inlineHelpText>
        <label>TestPicklistA</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>a0</fullName>
                </value>
                <value>
                    <fullName>a1</fullName>
                </value>
                <value>
                    <fullName>a2</fullName>
                </value>
                <value>
                    <fullName>a3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TestPicklistB__c</fullName>
        <description>This field has TestPicklistA as a controlling field and its values are restricted.</description>
        <inlineHelpText>This field has TestPicklistA as a controlling field and its values are restricted.</inlineHelpText>
        <label>TestPicklistB</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TestPicklistA__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>b0</fullName>
                </value>
                <value>
                    <fullName>b1</fullName>
                </value>
                <value>
                    <fullName>b2</fullName>
                </value>
                <value>
                    <fullName>b3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TestPicklistC__c</fullName>
        <description>This field has TestPicklistB as a controlling field and its values are restricted.</description>
        <inlineHelpText>This field has TestPicklistB as a controlling field and its values are restricted.</inlineHelpText>
        <label>TestPicklistC</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>TestPicklistB__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>c0</fullName>
                </value>
                <value>
                    <fullName>c1</fullName>
                </value>
                <value>
                    <fullName>c2</fullName>
                </value>
                <value>
                    <fullName>c3</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TestText__c</fullName>
        <label>TestText</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>FObjectTwo</label>
    <nameField>
        <displayFormat>FO2-{00000}</displayFormat>
        <label>FObjectTwo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FObjectTwos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

dx/force-app/main/default/objects/FObjectTwo__c/fields/TestCurrency__c.field-meta.xml
<CustomField>
    <fullName>TestCurrency__c</fullName>
    <label>TestCurrency</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

dx/force-app/main/default/objects/FObjectTwo__c/fields/TestDatetime__c.field-meta.xml
<CustomField>
    <fullName>TestDatetime__c</fullName>
    <label>TestDatetime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/forceea/objects/FObjectTwo__c/fields/TestLookup__c.field-meta.xml
<CustomField>
    <fullName>TestLookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TestLookup</label>
    <referenceTo>FObjectThree__c</referenceTo>
    <relationshipLabel>FObjectTwos</relationshipLabel>
    <relationshipName>FObjectTwos</relationshipName>
    <type>Lookup</type>
</CustomField>

dx/force-app/main/default/objects/FObjectTwo__c/fields/TestPercent__c.field-meta.xml
<CustomField>
    <fullName>TestPercent__c</fullName>
    <label>TestPercent</label>
    <precision>8</precision>
    <scale>3</scale>
    <type>Percent</type>
</CustomField>

dx/force-app/main/default/objects/FObjectTwo__c/fields/TestPhone__c.field-meta.xml
<CustomField>
    <fullName>TestPhone__c</fullName>
    <label>TestPhone</label>
    <type>Phone</type>
</CustomField>

force-app/main/forceea/objects/FObjectTwo__c/fields/TestUrl__c.field-meta.xml
<CustomField>
    <fullName>TestUrl__c</fullName>
    <label>TestUrl</label>
    <type>Url</type>
</CustomField>

metadata/src/classes/ForceeaExamples.cls
/*
  FORCEEA data factory framework (version 1.2.1)
  Copyright (C) 2018 Nikos Mitrakis

  This program is free software: you can redistribute it and/or modify it under the terms
  of the GNU General Public License as published by the Free Software Foundation,
  either version 3 of the License, or any later version.

  This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
  without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the GNU General Public License for more details.

  You can find a copy of the GNU General Public License at
  https://github.com/nmitrakis/Forceea/blob/master/LICENSE
*/

/**
 * @description Example scripts
 *   The following methods are written as test methods, but they are not.
 *   It is possible some methods to fail because of duplicate rules, validation rules, triggers, etc
 */
@isTest
public class ForceeaExamples {
  @isTest
  private static void createAccounts() {
    FObject obj = new FObject('Account');
    //obj.setDefinition('RecordTypeId', 'static value(xyz)');
    obj.setDefinition('Name', 'static value(Company_)');
    obj.setDefinition('Name', 'serial from(1) step(1) scale(0)');
    obj.setDefinition('NumberOfEmployees', 'random type(number) from(10) to(1000) scale(0)');
    obj.setDefinition('AnnualRevenue', 'random type(number) from(10000000) to(100000000) scale(3)');
    obj.setDefinition('Rating', 'random type(picklist) except(Hot)');
    obj.setDefinition('Industry', 'random type(picklist)');
    obj.setDefinition('Type', 'random type(picklist)');
    obj.setDefinition('Phone', 'static value("(353) ")');
    obj.setDefinition('Phone', 'random type(number) from (1111111) to (9999999)');
    obj.setDefinition('Site', 'random type(url)');
    obj.setDefinition('ShippingStreet', 'random type(street) group(shipping)');
    obj.setDefinition('ShippingPostalCode', 'random type(postalcode) group(shipping)');
    obj.setDefinition('ShippingCity', 'random type(city) group(shipping)');
    obj.setDefinition('ShippingState', 'random type(state) group(shipping)');
    obj.setDefinition('ShippingCountry', 'random type(country) group(shipping)');
    //obj.setDefinition('CreatedDate', 'random type(datetime) from(2010-01-01) to(2015-12-31)');
    //obj.setDefinition('CreatedById', 'random lookup(User) source(salesforce)');
    obj.insertRecords(true);
  }

  @isTest
  private static void createCases() {
    FObject obj = new FObject('Case');
    obj.setDefinition('AccountId', 'random lookup(Account) source(salesforce)');
    obj.setDefinition('ContactId', 'random lookup(Contact) source(salesforce)');
    obj.setDefinition('Origin', 'random type(picklist)');
    obj.setDefinition('Type', 'random type(picklist)');
    obj.setDefinition('Status', 'static value(Working)');
    obj.setDefinition('Subject', 'random type(text) minlength(50) maxlength(200)');
    obj.setDefinition('Reason', 'random type(picklist)');
    obj.setDefinition('Description', 'random type(text) minlength(50) maxlength(200)');
    obj.insertRecords(true);
  }

  @isTest
  private static void createContacts() {
    FObject obj = new FObject('Contact');
    obj.setDefinition('FirstName', 'random type(firstname) group(name)');
    obj.setDefinition('LastName', 'random type(lastname) group(name)');
    obj.setDefinition('Email', 'random type(email)');
    obj.setDefinition('LeadSource', 'random type(picklist)');
    obj.setDefinition('Birthdate', 'random type(date) from(1950-1-1) to(1982-12-31)');
    obj.setDefinition('Title', 'random type(list) value(Developer, CFO, Account Manager, CEO, Logistics Manager)');
    obj.setDefinition('Department', 'random type(list) value(Sales, Marketing, Accounting, Management)');
    obj.setDefinition('AccountId', 'random lookup(Account) source(salesforce)');
    obj.setDefinition('MailingStreet', 'random type(street) group(mailing)');
    obj.setDefinition('MailingPostalCode', 'random type(postalcode) group(mailing)');
    obj.setDefinition('MailingCity', 'random type(city) group(mailing)');
    obj.setDefinition('MailingState', 'random type(state) group(mailing)');
    obj.setDefinition('MailingCountry', 'random type(country) group(mailing)');
    obj.insertRecords(true);
  }

  @isTest
  private static void createEmailMessages() {
    FObject obj = new FObject('EmailMessage');
    obj.setDefinition('Subject', 'static value(Email)');
    obj.setDefinition('Subject', 'serial type(number) from(1) step(1) scale(0)');
    obj.setDefinition('TextBody', 'copy field(Subject)');
    obj.setDefinition('Incoming', 'static value(true)');
    obj.setDefinition('Status', 'static value(0)');
    obj.setDefinition('ParentId', 'random lookup(Case) source(salesforce)');
    obj.insertRecords(true);
  }

  @isTest
  private static void createLeads() {
    FObject obj = new FObject('Lead');
    obj.setDefinition('FirstName', 'random type(firstname) group(name)');
    obj.setDefinition('LastName', 'random type(lastname) group(name)');
    obj.setDefinition('Email', 'random type(email)');
    obj.setDefinition('Birthdate', 'random type(date) from(1950-1-1) to(1982-12-31)');
    obj.setDefinition('Title', 'random type(list) value(Developer, CFO, Account Manager, CEO, Logistics Manager)');
    obj.setDefinition('Industry', 'random type(picklist)');
    obj.setDefinition('AnnualRevenue', 'random type(number) from(1000000) to(10000000) scale(-3)');
    obj.setDefinition('Status', 'static value(Open)');
    obj.setDefinition('NumberOfEmployees', 'random type(list) value(10,20,30)');
    obj.setDefinition('Street', 'random type(street) group(other)');
    obj.setDefinition('PostalCode', 'random type(postalcode) group(other)');
    obj.setDefinition('City', 'random type(city) group(other)');
    obj.setDefinition('State', 'random type(state) group(other)');
    obj.setDefinition('Country', 'random type(country) group(other)');
    obj.insertRecords(true);
  }

  @isTest
  private static void createOpportunities() {
    FObject obj = new FObject('Opportunity');
    obj.setDefinition('Name', 'static value(Opp)');
    obj.setDefinition('Name', 'serial from(1) step(1) scale(0)');
    obj.setDefinition('Amount', 'random type(number) from(1000000) to(10000000) scale(-3)');
    obj.setDefinition('StageName',  'random type(picklist)');
    obj.setDefinition('CloseDate', 'random type(date) from(2017-01-01) to(2017-12-31)');
    obj.insertRecords(true);
  }

  @isTest
  private static void createTasks() {
    FObject obj = new FObject('Task');
    obj.setDefinition('Subject', 'random type(picklist)');
    obj.setDefinition('Priority', 'random type(picklist)');
    obj.setDefinition('Status', 'random type(picklist)');
    obj.setDefinition('Type', 'random type(picklist)');
    obj.setDefinition('WhatId', 'random lookup(Account) source(salesforce)');
    obj.setDefinition('ActivityDate', 'random type(date) from(2017-10-1) to(2017-12-31)');
    obj.insertRecords(true);
  }

  @isTest
  private static void createEvents() {
    FObject obj = new FObject('Event');
    obj.setDefinition('Subject', 'random type(picklist)');
    obj.setDefinition('Type', 'random type(picklist)');
    obj.setDefinition('WhoId', 'random lookup(Contact) source(salesforce)');
    obj.setDefinition('ActivityDatetime', 'random type(datetime) from(2017-10-1) to(2017-12-31)');
    obj.setDefinition('DurationInMinutes', 'random type(number) from(1) to(10) scale(0)');
    obj.insertRecords(true);
  }

  @isTest
  private static void createChatterFeeds() {
    FObject obj = new FObject('FeedItem');
    obj.setDefinition('Body', 'random type(text) minlength(50) maxlength(500)');
    obj.setDefinition('ParentId', 'random lookup(Contact) source(salesforce)');
    obj.setDefinition('Status', 'static value(Published)');
    obj.setDefinition('Type', 'static value(TextPost)');
    obj.setDefinition('Title', 'random type(text) minlength(50) maxlength(250)');
    obj.insertRecords(true);
  }

  @isTest
  private static void createtUsers() {
    FObject obj = new FObject('User', 1);
    obj.setDefinition('ProfileId', 'static lookup(Profile) field(Name) value(System Administrator) source(salesforce)');
    //obj.setDefinition('UserRoleId', 'static lookup(UserRole) field(Name) value(CEO) source(salesforce)');
    obj.insertRecords(false);
  }

  @isTest
  private static void createFObjectOneRecords() {
    FObject obj = new FObject('FObjectOne__c');
    obj.setDefinition('TestCheckbox__c', 'static value(true)');
    obj.setDefinition('TestCurrency__c', 'random type(number) from(1) to(100) scale(0)');
    obj.setDefinition('TestDate__c', 'random type(date) from(2017-1-1) to(2017-12-31)');
    obj.setDefinition('TestDatetime__c', 'random type(datetime) from(2017-1-1) to(2017-12-31)');
    obj.setDefinition('TestDecimal__c', 'random type(number) from(1) to(100) scale(3)');
    obj.setDefinition('TestEmail__c', 'random type(email)');
    obj.setDefinition('TestInteger__c', 'random type(number) from(1) to(100) scale(0)');
    obj.setDefinition('TestLookup__c', 'random lookup(FObjectTwo__c) source(salesforce)');
    obj.setDefinition('TestMultiPicklistA__c', 'random type(picklist)');
    obj.setDefinition('TestPercent__c', 'random type(number) from(1) to(100) scale(1)');
    obj.setDefinition('TestPhone__c', 'static value(2102525125)');
    obj.setDefinition('TestPicklistA__c', 'random type(picklist) except(a0)');
    obj.setDefinition('TestPicklistB__c', 'random type(picklist)');
    obj.setDefinition('TestPicklistC__c', 'random type(picklist)');
    obj.setDefinition('TestPicklistD__c', 'random type(picklist) except (d0,d1)');
    obj.setDefinition('TestText__c', 'random type(string) minlength(10) maxlength(30) startwith(lower) include(lower,upper,digit)');
    obj.setDefinition('TestTextArea__c', 'random type(string) minlength(10) maxlength(30) startwith(lower) include(lower,upper,digit)');
    obj.setDefinition('TestTextAreaLong__c', 'random type(string) minlength(50) maxlength(200) startwith(lower) include(lower,upper,digit)');
    obj.setDefinition('TestTextAreaRich__c', 'random type(string) minlength(50) maxlength(200) startwith(lower) include(lower,upper,digit)');
    obj.setDefinition('TestTextRequired__c', 'random type(string) minlength(10) maxlength(20) startwith(upper) include(lower,upper)');
    obj.setDefinition('TestTime__c', 'static value(22:10:05)');
    obj.setDefinition('TestUrl__c', 'random type(url)');
    obj.insertRecords(true);
  }
}